### ISSUE TITLE
Fixing issues after Testing

### ISSUE THREAD

**Issue by faithfulmaster** [Bridgeconn/VachanAppReact#1]
1. Remove signed key
2. Fix search issue
3. Fix section heading position

**Comment by neetuy** [comment]
![Screenshot_1594730670](https://user-images.githubusercontent.com/24825770/87504978-5c513f80-c685-11ea-9707-244a1f9eb973.png)
![Screenshot_1594730690](https://user-images.githubusercontent.com/24825770/87505022-7b4fd180-c685-11ea-9050-4799616c209d.png)
![Screenshot_1594730739](https://user-images.githubusercontent.com/24825770/87505061-928ebf00-c685-11ea-9344-5c1dd6195020.png)
![Screenshot_1594730747](https://user-images.githubusercontent.com/24825770/87505074-9c182700-c685-11ea-948d-9773d60d6034.png)

1.Removed signed key , 
2.Fixed search issue 
3.Fixed issue of section and chapter heading
