### ISSUE TITLE
Reading Plan : It is not possible to view the plan of previous weeks or dates on scrolling upwards

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#107]
In the Bible reading plan, beyond a particular date on scrolling upwards on the calendar, it is not possible to view the plan of the previous weeks or dates .
Note:
On scrolling downwards ,it is possible to view the plan of the following weeks to any date.

**Comment by neetuy** [comment]
Scroll upward is possible up to some limited value, not possible beyond it. It is library issue(I'm using third party library for calendar). For this issue need to discuss with @samuelanthrayose .

**Comment by samuelanthrayose** [comment]
@neetuy As discussed in yesterday's meeting, if this is easily do-able, do it, else - we can take this up as an enhancement later on.

**Comment by neetuy** [comment]
Ok,moving it to backlog to take up later as enhancement.
