### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by rinsingh** [Bridgeconn/VachanAppReact#12]
1. Login with Google:  Shows list of gmail ids configured on Mobile. But after you select an id - it doesn't do anything.
2. Reset password: Takes you to screen to give email id for which password is to be reset, and then hangs
3. Create new login credentials: Creates login, but it is through a web of messages and not smooth

**Comment by AnnCherianA** [comment]
Gmail authentication works fine. 
New login credentials also works.
Reset password works fine.
