### ISSUE TITLE
Previously selected chapter is highlighted while selecting the chapter.

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#129]
@AnuMonachan noted that if we choose a Book and chapter say John 4 and switch to any book -NT or OT the previously selected chapter 4 would display in bold format. This is preferred for the book say John but may not be required for the chapter.

**Comment by AnnCherianA** [comment]
Need to check with @samuelanthrayose on whether this is ok to highlight or not.

**Comment by AnnCherianA** [comment]
![image](https://user-images.githubusercontent.com/74647279/125638622-a29fc739-32b3-423c-9665-bef9468c4aa8.png)

If we want to select another book, say Mark 4, the book selector displays  the previous book Matthew in bold which is expected
but while selecting the chapter ,the previous chapter 28 is displayed in bold as well.

**Comment by samuelanthrayose** [comment]
@AnnCherianA I guess this should be fine, as we are showing the previously selected book and chapter to the user. What if the user wants to select some other chapter in the same book he was reading? Then this highlight of the chapter number is useful here.

**Comment by AnnCherianA** [comment]
Thank you Samuel. @neetuy  we can then close this.

**Comment by AnnCherianA** [comment]
As rightly pointed out by @samuelanthrayose  since this feature is helpful for the user, we can close this.
