### ISSUE TITLE
Downloaded (offline) Bible does not have link between books

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#130]
The next and previous chapter navigation which was implemented for online books is not available in the offline mode.
Found during unit testing 
Reported by @neetuy 

Expected : The link between books and chapters should be available in offline mode as well.

**Comment by AnnCherianA** [comment]
We can take this up for further releases as the feature works for online Bibles.

**Comment by neetuy** [comment]
As we don't have information from api for  prev and next book or chapter for offline bible.We can take it later as enhancement.

**Comment by neetuy** [comment]
moving to backlog to take up it as enhancement.
