### ISSUE TITLE
Audio List  from Drawer

### ISSUE THREAD

**Issue by neetuy** [Bridgeconn/VachanAppReact#145]
Add a Audio option on drawer which will have all available audio in a particular language ,when user select audio from list navigate to Bible screen and play selected Audio.

**Comment by Poojanavgurukul** [comment]
please review

**Comment by AnnCherianA** [comment]
Linking issue observed for this issue
https://github.com/Bridgeconn/VachanAppReact/issues/155

**Comment by LijuJacob08** [comment]
had tested this feature. Audio option on drawer which is having all available audio in a particular language ,when user select audio from list navigate to Bible screen and play selected Audio.
hence moving it done.
