### ISSUE TITLE
Bible stories : Incomplete text for the last character of the first  Hindi Bible story

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#149]
The last character of the first Bible story is slightly cut off.This issue was identified as part of testing the below main issue

https://github.com/Bridgeconn/VachanAppReact/issues/126
Since issue 126 is fixed, raising a separate issue. This is a very low priority issue since it is only for one story of the Hindi Bible stories list

**Comment by AnnCherianA** [comment]
![image](https://user-images.githubusercontent.com/74647279/130951921-7ec2ce28-a22a-4f49-9e83-ea1b7eccff7d.png)

**Comment by LijuJacob08** [comment]
last tested it on 1.3.4 alpha11
no change has been observed.
