### ISSUE TITLE
Bookmarked chapter is not showing in booksmarked chapter list. 	 	 	 	 	 	

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#157]
Bookmarked chapter is not showing in bookmarked chapter list.

**Comment by AnnCherianA** [comment]
bookmarked chapters now display in the list of bookmarks

**Comment by LijuJacob08** [comment]
had tested it, results were as expected , ie the bookmarked chapter are displayed in list of bookmarks. hence moving it done.
