### ISSUE TITLE
Search does not display results for a long time

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#161]
On searching a word , it displays '0 search results' for some time before loading the search results.(medium)

**Comment by AnnCherianA** [comment]
![image](https://user-images.githubusercontent.com/74647279/136440380-f477a174-410b-46df-8d59-8b27df6523f7.png)

**Comment by LijuJacob08** [comment]
tried searching few words/ verse. results were as expected and loading time was fine.
hence moving to done.
