### ISSUE TITLE
Infographics not available alert is hidden/overlaps with the Infographics header

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#164]
The alert displayed when Infographics is not available hides/overlaps the Infographics header (low)

**Comment by AnnCherianA** [comment]
Linking the main issue -React native version ugprade

**Comment by AnnCherianA** [comment]
https://github.com/Bridgeconn/VachanAppReact/issues/95

**Comment by AnnCherianA** [comment]
![image](https://user-images.githubusercontent.com/74647279/136440524-cdb25031-83ae-4ae3-a6cc-026f58110b76.png)

**Comment by AnnCherianA** [comment]
@neetuy  please move to Product Backlog- the issue exissts

**Comment by LijuJacob08** [comment]
last version tested on- 1.3.4 aplha 11
