### ISSUE TITLE
Enhancement- Audio  for a chapter continues to play even on switching to next chapter

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#167]
-Enhancement : If an audio file is playing (John1) and if we switch to the next chapter, the audio of John 2 continues to play . (To be discussed in meeting whether we should continue to play the audio or pause whenever user switches the chapter.)

**Comment by AnnCherianA** [comment]
@LijuJacob08  please share the current status of this issue

**Comment by LijuJacob08** [comment]
Issue is till there.

switched the chapter while the audio was playing for a chapter, audio did'nt  paused/stopped  but it started playing for the new chapter.

**Comment by LijuJacob08** [comment]
moving to in progress
