### ISSUE TITLE
App crashing while while clicking on "NO" for "Do you Want to download the pdf for current chapter?" prompt message

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/VachanAppReact#170]
(VachanGo 1.3.2-alpha.4 apk)
while trying to click on "No" for  the "Do you Want to download the pdf for current chapter?" prompt message .

followed step sequence (screenshots)  

**click on 'Print/Save' button**
![image](https://user-images.githubusercontent.com/93033055/139379035-64674712-1325-409c-a4cb-76cec92fca01.png)

**click on "No"** 
![image](https://user-images.githubusercontent.com/93033055/139379187-e2313a2d-bf59-4b30-b751-2e572b6e23a7.png)

**App crashing**
![image](https://user-images.githubusercontent.com/93033055/139379235-e9cdf445-aa17-4f3d-bc33-f0e155ca4e01.png)

**Comment by AnnCherianA** [comment]
@Liju please verify the issue and update the status

**Comment by LijuJacob08** [comment]
issue is fixed and can be moved to 'Done'.

attaching the screenshots

![image](https://user-images.githubusercontent.com/93033055/140029372-0086a24b-2dab-474d-9864-4a5a3fee4b1b.png)

 after clicking on "NO"
![image](https://user-images.githubusercontent.com/93033055/140029587-3d03aa67-056d-44b7-9cb3-5e256ec4580a.png)

**Comment by LijuJacob08** [comment]
moving to done
