### ISSUE TITLE
incorrect arrows used for expand and Collapse (Download more Bibles/language)

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/VachanAppReact#172]
(VachanGo V1.3.2 apha 4 apk)
**Issues Description**:
In Download more Bibles/Languages -> collapse and expand arrows are pointing otherway around.

  ![image](https://user-images.githubusercontent.com/93033055/139590246-f36e8135-c5bc-481e-a52a-868b4c710866.png)

**Comment by AnnCherianA** [comment]
Review Comment:
@LijuJacob08  Screenshot has been perfectly captured and marked with the right colors in this issue. Please follow the same norms in other images as well.

**Comment by AnnCherianA** [comment]
@LijuJacob08 please verify this issue

**Comment by LijuJacob08** [comment]
**Changes observed**: -all collapse(up) arrows are removed. looks fine.
![image](https://user-images.githubusercontent.com/93033055/140015811-d5b237c1-ddda-4cbf-ad2a-345c9adcf48a.png)

**Comment by LijuJacob08** [comment]
moving to done
