### ISSUE TITLE
For lang where video in not available ,clicking on 'video' will open a page with never ending loading

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/VachanAppReact#173]
(VachanGo V1.3.2 apha 4 apk)
Issue Description:
the video icon for those lang's for whom the video is not available is  directing to page with never ending load.
![image](https://user-images.githubusercontent.com/93033055/139591715-702220d2-df19-441d-8662-665d08fddd8e.png)

this needs fix on both top icon as well as for the video option present in the left menu panel.
Langages with this issue-
(Assamese ,Bilaspuri ,Dogri ,Gujarati ,Haryanvi ,Kannada ,Marathi ,Nagamese ,Odia ,Punjabi ,Tamil ,Urdu)

Suggestion : -
- we have   
![image](https://user-images.githubusercontent.com/93033055/139591458-4d3d338e-5318-4bab-9c49-43cb5f8fe02f.png)
 symbol where audio file is not available,
- for the video option on the left panel can direct to the page with message "Video not available for <language>"

**Comment by AnnCherianA** [comment]
@LijuJacob08 please verify this issue

**Comment by LijuJacob08** [comment]
Issue is fixed , can be moved to done.
attaching the screenshot
![image](https://user-images.githubusercontent.com/93033055/140059723-2bbae813-3a42-4a59-a3cc-bc1906018b80.png)

**Comment by LijuJacob08** [comment]
moving to done
