### ISSUE TITLE
expand /collapse arrows in the History section - are not pointing correctly and not changing as they are expected to change .

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/VachanAppReact#174]
(VachanGo v1.3.2 aplha 5 apk)

**Issue Description**:-
expand /collapse arrows in the History section - are not changing as they are expected to change and for the latest history it's incorrect.

![image](https://user-images.githubusercontent.com/93033055/139596102-555628bd-988f-4aec-931b-46f31e34bd56.png)

![image](https://user-images.githubusercontent.com/93033055/139596071-c297b654-3ff9-4edf-aaeb-a9d96c2da102.png)

**Expected behavior** : -
- should point up when it's in expanded.
- should point down when it's collapsed.

**Comment by AnnCherianA** [comment]
@LijuJacob08  please verify this issue

**Comment by AnnCherianA** [comment]
Review comments:
@LijuJacob08  please include only the part of the screenshot that is relevant to the issue. Edit the image such that info related to the phone does not show (Network, Battery,etc)

**Comment by AnnCherianA** [comment]
@LijuJacob08 please mark observed issues in red as much as possible on the screenshot.

**Comment by LijuJacob08** [comment]
Issue is not fixed.
now the the previous history ( i.e yesterday, 1 week ago) are showing the the up arrow.

![image](https://user-images.githubusercontent.com/93033055/140023765-07fc1120-ad72-46ea-933a-2bb22699741f.png)

**Comment by LijuJacob08** [comment]
moving to in progress
