### ISSUE TITLE
Content load issue in commentary

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/VachanAppReact#175]
(VachanGo v1.3.2 aplha 5 apk)

**Issue Description**:-
content load issue in commentary section :-eg maps are not loading eg .in Gujarati and Marathi-> Matthew chapter1 there are maps which are not loading.

![image](https://user-images.githubusercontent.com/93033055/139596406-edf16ebe-6718-46e3-8acf-0a818544640d.png)

**Comment by AnnCherianA** [comment]
@LijuJacob08 please verify this issue

**Comment by LijuJacob08** [comment]
Issue is not fixed.

![image](https://user-images.githubusercontent.com/93033055/140016321-19d392ef-2bea-4d6d-b9fb-611c52f98b6e.png)

**Comment by LijuJacob08** [comment]
moving to in progress
