### ISSUE TITLE
divider missing in lang and stories dropdown (OBS)[VachanGo 1.3.4 apha 9. apk] 

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/VachanAppReact#198]
**Issue Description:**
in the lang and stories drop down-> menu item divider is visile after every two menu items(it's in OBS page).
**Expected result:**
there should be a divider after each menu item in the drop down.

Attaching the screenshot
![WhatsApp Image 2022-03-22 at 10 37 03](https://user-images.githubusercontent.com/93033055/159412108-93e104b9-ccc4-4ee4-8cee-67ceaa36ab78.jpeg)
![WhatsApp Image 2022-03-22 at 10 37 03 (1)](https://user-images.githubusercontent.com/93033055/159412136-6cad8c91-589b-482b-8a29-63926396c7a4.jpeg)

**Comment by AnnCherianA** [comment]
@LijuJacob08 please mention the apk version in which this observation was found
