### ISSUE TITLE
long words spelling displayed in two lines

### ISSUE THREAD

**Issue by JesniJ** [Bridgeconn/VachanAppReact#220]
n parallel view , for 1st chapters commentaries certain words like Background " Backgroun "in first line and "D" appears in next line
![spelling_split2](https://user-images.githubusercontent.com/102143707/168251080-33c0415f-31f1-4263-a77e-e0043e05256d.png)
![spelling splitt](https://user-images.githubusercontent.com/102143707/168251081-408d0103-0e6d-4387-8f1c-42a018635b9b.png)
.

**Comment by samuelanthrayose** [comment]
@JesniJ This is not an issue, as that word length is so-long that it cannot be displayed in a single line. So the text is formatted automatically based on the screen size.
