### ISSUE TITLE
Downloaded Bible

### ISSUE THREAD

**Issue by Poojanavgurukul** [Bridgeconn/VachanAppReact#273]
on clicking next and previous arrows content is not updating

**Comment by AnnCherianA** [comment]
@Poojanavgurukul  can we please discuss this issue? QA is supposed to be involved right

**Comment by AnnCherianA** [comment]
@Poojanavgurukul  why are two issues being created. Is this part of a release. Please keep QA informed.

**Comment by Poojanavgurukul** [comment]
by mistake
