### ISSUE TITLE
Issues in release 1.0.1

### ISSUE THREAD

**Issue by samuelanthrayose** [Bridgeconn/VachanAppReact#35]
1. The video icons in the drawer and the top bar do not match, the icon is also there in the hints sections
2. If you change the book in the parallel bible the book name at the top does not change in the parallel bible
3. The section headings are not shown in the parallel bible. The bible only shows the first section heading not the remaining see the website for chapters with more than one section heading in a chapter.
4. There is a icon in help->hints a person reading a book, am not sure if it is there in the app. If not there, remove it.
5. If you open up the video from the drawer, the new testament video gets repeated for each book.

**Comment by AnnCherianA** [comment]
Verified that all the above issues have been fixed.
The new testament video repetition does not occur any more.
The icon of a person reading a book does not appear in Help->Hints.
The section headings appear for the parallel view  as well.
On changing the book in the parallel view, the book name change does reflect on the top bar as well.
The video icon reflecting in the top is now displayed for the drawer bar as well.
