### ISSUE TITLE
Spacing between sign and in in the Profile page.

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#36]
The Profile sign in option should have a space between sign and in.
Steps:
From the Drawer bar, select Login /Sign Up
Observation : There is no space between sign and in
Expected Result: 
![Profile Sign in spacing](https://user-images.githubusercontent.com/74647279/99516950-cd4a9000-29b4-11eb-9d15-fd9ed7756f42.jpg)
The sign in option is to have a space between the two words

**Comment by neetuy** [comment]
Fixed Issue of spacing between signIn and SignUp button pushed code to version_1.0.1_fixes

**Comment by AnnCherianA** [comment]
Verified that Sign in is spaced correctly.
![Verified VG sign in spacing](https://user-images.githubusercontent.com/74647279/102599821-09077f80-4144-11eb-87c6-dfe36aad461b.jpg)
