### ISSUE TITLE
The Note Section headings of the Hindi Bible  are of the format Chapter followed by hyphen and the verse.

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#37]
Issue description : In the Note headings  ,the chapter and verse are separated by hyphen.
Version : Vachan Go 1.0.1
Steps:
i) Select the Hindi version
ii) Sign in to the profile
iii) From the drawer bar, select Notes
Observation:
The headings of the notes  listed  in the Hindi version are of the  format Book name , Chapter followed by hyphen and the verse
Eg John 11-3,4
Expected Result:
In the Note section headings, the chapter and verse should be separated by colon .Eg: John 3:16,17 
![The Note Section headings should have colons separating the chapter and the verse](https://user-images.githubusercontent.com/74647279/99519622-1e0fb800-29b8-11eb-8dfa-09f7eb0875a2.jpg)

**Comment by neetuy** [comment]
Fixed issue of hyphen, removed hyphen added colon and pushed code to version_1.0.1_fixes branch

**Comment by AnnCherianA** [comment]
Verified that in the Note Section headings the chapter and verse in the Hindi Bible are separated by a colon.
![VG _Verfied that chapter and verse in the note section heading are separated by comon](https://user-images.githubusercontent.com/74647279/102046661-bfe0c400-3e01-11eb-9bd6-ea817b5c2142.png)
Also opened the note and verified that the contents are displayed correctly.
