### ISSUE TITLE
Sync /Refresh issue :The note icon does not appear on the app as soon as a note is created on the website

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#38]
Issue description : When a note is created for a verse via the website, it takes a while for the note icon to reflect on the app.

Steps:
Create a note for a verse on the website
Now open the app and navigate to the same verse.
Observation:
The note icon does not display alongside the verse in the App. This seems to be a refresh issue.
Work Around: Select the Note option from the bottom bar of the app. The  notes would be listed here
                        Also, since the window is refreshed by the above step, there are chances for the note icon to reflect beside the 
                        verse.
Expected Result:
The note icon should be displayed beside the verse as in the website.
![Vachan online note icons ](https://user-images.githubusercontent.com/74647279/99522689-f9b5da80-29bb-11eb-9cfd-6fc2efacd531.jpg)
![The note icon takes a while to reflect on the app when a note is created via the website](https://user-images.githubusercontent.com/74647279/99522771-10f4c800-29bc-11eb-9bf2-b879921c9a75.jpg)

**Comment by neetuy** [comment]
Fixed This notes sync issue and pushed code to branch 'version_1.0.1_fixes'

**Comment by AnnCherianA** [comment]
Verified the fix 
**Verification comments:**
Observation : The moment a note is created on the website, it reflects immediately on the App.
Wrt the note content sync, tested a few times for which the sync times are as follows
Iteration 1:  Network speed: 20Mbps  ,sync time -few seconds,  
Iteration 2: Network speed: 3.49 Mbps, sync time:  1 min

The note sync time is dependent on the network speed.
![VG -Verified VG note sync](https://user-images.githubusercontent.com/74647279/100072010-b77c1580-2e61-11eb-881c-97504ccf07a3.png)
