### ISSUE TITLE
Note Section heading: The Bible Version in the Note heading begins with a small letter

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#39]
Issue description : The names of the Version in the Note section heading begins with a small letter eg hin-IRV
 
**Steps:**
Create a note for a verse on the website
From the drawer panel, select Notes 
Check the list of notes
Observation:
The Bible version begins in small letter eg hin-IRV
Expected Result:
The Bible Version should begin with a capital letter eg Hin-IRV
![The Version name of the books in the Note should begin with a Captial letter](https://user-images.githubusercontent.com/74647279/99796851-31578a80-2b54-11eb-8f45-6018d816c716.png)

**Comment by samuelanthrayose** [comment]
Have this been fixed ? @neetuy

**Comment by neetuy** [comment]
Yes ,this issue is fixed

**Comment by AnnCherianA** [comment]
Verified that the Bible version in the note section heading begins with a capital letter .
![VG-Verified that note section headings begin with a capital letter](https://user-images.githubusercontent.com/74647279/102856364-5178b300-444c-11eb-829a-6ac209d99664.jpg)
