### ISSUE TITLE
Bookmarks should be spelt as one word

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#40]
Issue description: Bookmarks is spelt as BookMarks

Steps: From the drawer panel, verify whether Bookmarks appears as one word
Observation :Bookmark is spelt as BookMarks
Expected Result : It should display as Bookmarks.
![VGo bookmark ](https://user-images.githubusercontent.com/74647279/99936034-271dd200-2d88-11eb-9a01-9e987396cf47.jpg)

**Comment by samuelanthrayose** [comment]
@neetuy Has this been fixed?

**Comment by neetuy** [comment]
Yes This issue is fixed

**Comment by AnnCherianA** [comment]
Verified that bookmarks is now displayed as one word in the drawer panel.
![VG-Verified that bookmarks is now displayed correclty in the drawer panel](https://user-images.githubusercontent.com/74647279/102753676-c2a76000-4391-11eb-999c-8fee1e616967.jpg)
