### ISSUE TITLE
Bookmarks:The book name and chapter should not have a colon between them

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#41]
Issue description : The book name and chapter in the bookmarks should not be separated by a colon

Steps:
From the drawer bar, select Bookmarks
Select  the version and chapter to be bookmarked.
Observation:
In the bookmark heading, the book and chapter are separated by colon , Eg John :16
Expected Result:
The book and chapter are to only have a space and the colon is to be removed. Eg John 16
![The book name an chapter display colon in between them](https://user-images.githubusercontent.com/74647279/99936905-4f0e3500-2d8a-11eb-84bf-086350f5e4d6.jpg)

**Comment by samuelanthrayose** [comment]
@neetuy Any update on this issue?

**Comment by neetuy** [comment]
This issue is fixed Fixed

**Comment by AnnCherianA** [comment]
Verified that the colon  between the bookname and chapter is removed.
![VG-The colon between book name and chapter has been removed from the bookmark heading](https://user-images.githubusercontent.com/74647279/102754094-73adfa80-4392-11eb-82a1-530e32eb5874.png)
