### ISSUE TITLE
Bookmarks: A bookmark should display the version of the Bible for a bookmarked chapter

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#45]
Issue description : The version of the Bible for a bookmarked chapter should be displayed
Steps:
Select any version of the Bible (Say English-KJV) 
Select a chapter and bookmark it.

Observation:
The bookmark heading does not display the Bible version of the chapter that is bookmarked.
Expected Result:
The bookmark heading should display the version of the Bible for the chapter that is bookmarked.
![VG-Bookmark should display the version of the Bible (English) for the chpater that is bookmarked](https://user-images.githubusercontent.com/74647279/102753139-ad7e0180-4390-11eb-995a-246fb2730430.jpg)

**Comment by neetuy** [comment]
It is Fixed

**Comment by AnnCherianA** [comment]
Verified that the  bookmark displays the version of the Bible for a chapter that is bookmarked.
![VG-Verified that the Bible version is displayed in the bookmark section heading](https://user-images.githubusercontent.com/74647279/102755016-ce942180-4393-11eb-8b5d-dd6f3d9947db.jpg)
