### ISSUE TITLE
Multi-Color Highlights

### ISSUE THREAD

**Issue by samuelanthrayose** [Bridgeconn/VachanAppReact#46]
Add multi-color highlighting feature

1. New JSON structure decided
users>uid>highlights>sourceId(10)>jhn(book)>1(chapter)>["1:a","10:c"](verse:color code)

2. Color codes
a:#fffe00 (yellow) 
b:#5dff79 (green) 
c:#56f3ff (cyan) 
d:#ffcaf7  (pink) 
e:#ffc66f (orange)

3. How the Colors Look : [Doc link](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.wiki/tab::bcd244c0-6d2d-4925-aa3e-88689340288a?context=%7B%22subEntityId%22%3A%22%7B%5C%22pageId%5C%22%3A3%2C%5C%22sectionId%5C%22%3A75%2C%5C%22origin%5C%22%3A2%7D%22%2C%22channelId%22%3A%2219%3Ada158eb0344e43bbafde58bf14f8df44%40thread.tacv2%22%7D&tenantId=dc5352cb-2fb1-4f19-a355-61b4398ec2e1)

As of now, have 5 fixed color highlight options which show in a popup when the verse is selected for highlight i.e. you click the highlight button on the screen

**Comment by AnnCherianA** [comment]
Verified that multicolour highlight works  for various use cases.
![VG-Verified the implementation of multicolor highlights](https://user-images.githubusercontent.com/74647279/103287490-a4cca180-4a08-11eb-9a4e-498bc70c7cba.jpg)
