### ISSUE TITLE
Add padding/spacing between the book/chapter dropdown

### ISSUE THREAD

**Issue by samuelanthrayose** [Bridgeconn/VachanAppReact#48]
Add padding between the book/chapter dropdown

**Comment by AnnCherianA** [comment]
Issue description: 
Including Padding  between  the book or chapter dropdown would enable better usability

Steps:
From the Vachan Go App. select a book name and chapter.
Observation : The drop down arrows for the book/chapter are placed too close, resulting in a crowded UI
Expected result: Include enough padding such that the drop down arrows for book /chapter can be easily selected.
![VG-There should be enough space betw the book and chapter dropdown](https://user-images.githubusercontent.com/74647279/103288272-810a5b00-4a0a-11eb-9959-3ee18cc320f5.png)
