### ISSUE TITLE
In the Highlights section heading, there is a colon between the bookname and chapter

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#50]
Issue description:
A colon is included between the book name and chapter in the Highlights section heading

Steps:
From the App, select a verse  from a Bible passage
From the drawer panel, select Highlights.
Observation : A colon is displayed between the book name and chapter in the Highlights section heading.

Expected result: Remove the colon that lies between the bookname and chapter
![Vachan Go-Highlights header -The colon between the book name and chapter should be removed](https://user-images.githubusercontent.com/74647279/103289312-e6f7e200-4a0c-11eb-98f4-d3182e60239f.jpg)

**Comment by neetuy** [comment]
Fixed
