### ISSUE TITLE
History header:Remove the colon between the book name and chapter.

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#51]
Issue description:
A colon is included between the book name and chapter in the History section heading

Steps:
From the App, select a verse from a Bible passage
From the drawer panel, select History
Select the day (say 'Today') from the list
Observation : A colon is displayed between the book name and chapter in the History section heading.

Expected result: Remove the colon that lies between the bookname and chapter in the History header 
![VG-History header -Remove the colon between the book name and chapter](https://user-images.githubusercontent.com/74647279/103289688-cc723880-4a0d-11eb-840e-cd3dfb167e78.jpg)

**Comment by neetuy** [comment]
Fixed
