### ISSUE TITLE
Parallel Bible :The color tray that displays for highlighting in the first pane is still visible upon selecting another book in the parallel Bible view

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#52]
Issue description:
The color tray that displayed for highlighting in the single pane , is still visible, upon selecting a new book in the parallel Bible view

Steps:
From the App, select a verse from a Bible passage
Now the color tray displays for the purpose of highlighting. 
Select the parallel Bible option, choose another book in the second pane.
Observation : The color tray that displayed for highlighting in the first pane is still visible upon selecting another book in the parallel Bible view

Expected result:  Since the highlight option is not functional in the parallel view, t
![VG-The color tray should not be visible in the parallel Bible view](https://user-images.githubusercontent.com/74647279/103292080-24f80480-4a13-11eb-97d7-f1de08394a52.jpg)
he color tray should not be visible in the parallel Bible view

**Comment by neetuy** [comment]
Fixed
