### ISSUE TITLE
 Download (Bible) icon does not respond on touch. The area needs to be enlarged.

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#55]
Issue description: The Download (Bible) icon does not respond on touch. The area needs to be enlarged.
Steps:
From the language list, select a language say Hindi
Hover over the Download icon and select it.
![VG-Enlarge the Download icon touch area](https://user-images.githubusercontent.com/74647279/107781798-52ec9a80-6d6e-11eb-952a-ab91c04f3da6.jpg)

Observation :
Clicking the Download icon, does not download the Bible.
Expected Result:
Selecting The Download icon should start downloading the selected Bible

**Comment by neetuy** [comment]
Issue has been fixed in 1.1.1 release.
