### ISSUE TITLE
Infographics alert - Display for a longer time

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#56]
Issue description: The infographics alert should be displayed for a longer time so that the user can read it.
Steps:
Select a language for which Infographics is not available
Observation:
The alert saying No infographics available  appears at the top as expected
 However, it displays only for a few seconds and it may not catch the user's attention.
![VG-Infographics-Alert message is displayed only for few seconds](https://user-images.githubusercontent.com/74647279/107787180-c42f4c00-6d74-11eb-9fc6-d282458e87b3.jpg)

**Comment by neetuy** [comment]
Issue has been fixed in 1.1.1 release.
