### ISSUE TITLE
Parallel Bible-Only the chapter displays and the book does not appear

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#57]
Issue Description ; On selecting parallel view, the chapter alone displays for a while before displaying the book name.
i) On selecting the parallel Bible, the chapter alone displays for a few seconds and then the book appears only after a while.
For eg, if we are on John 1 (English KJV) and on accessing the parallel Bible (Hindi IRV) only the chapter ie 1 displays, and the book appears only after a while
Note :This is a regression and was not observed in the previous test release
Steps:
Select a language say English KJV and book -John 1
Access the parallel Bible say Hindi IRV
Observation:
Only the chapter displays and the book appears only after a while
Expected Result
Both the book and chapter are to display in the parallel Bible header.
![VG-Parallel Bible- In the header, Chapter alone displays without book and version](https://user-images.githubusercontent.com/74647279/107787941-c80f9e00-6d75-11eb-8035-d69ad7de10ae.jpg)

**Comment by neetuy** [comment]
Issue has been fixed in 1.1.1 release.
