### ISSUE TITLE
Select verse -Verse still selected even on switching to Parallel view without performing any user operation

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#59]
Issue Description ;
If a verse is selected, it continues to be selected even on switching to parallel view, without performing any operation (Write Notes/highlight/share) 

Steps:
Select a verse.
The color tray is displayed
Now try switching to the parallel view or other icon or feature
Observation:
The selected verse , even on switching to the parallel view continues to be selected.
Expected:
It should pop a question as to what the user desires to do next -Writ Notes/Highlight or Share before switching to parallel view.
An alert asking what operation the user wants to perform next (Share or Write Notes or Highlight etc) is to be thrown.
![VG-Verses highlighted on selection](https://user-images.githubusercontent.com/74647279/107790301-a532b900-6d78-11eb-9f5b-629a6e6b1ef6.jpg)
![VG-Parallel View -Verses highlighted on selection continues to be selected without any alert for user's choice](https://user-images.githubusercontent.com/74647279/107790386-b8458900-6d78-11eb-9499-9577d0954a1d.jpg)

**Comment by neetuy** [comment]
Issue has been fixed in 1.1.1 release.
