### ISSUE TITLE
Parallel Bible-Refresh Issue- Previously selected book loads

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#60]
Issue Description ;
Refresh issue in Parallel Bible: The app takes a while  at times to load the selected version/book in the Parallel Bible pane. It loads the previously selected book first.

Steps:
In the parallel select any language and book in the right pane

Now try switching to a different language/Bible
Observation:
The selected language and book takes a while to load.
It loads the previously selected book and language for a while
Expected:
The moment a new language/book is selected ,it  should load the preferred selection

**Comment by neetuy** [comment]
Issue has been fixed in 1.1.0 release.

**Comment by neetuy** [comment]
Issue has been fixed in 1.1.1 release.
