### ISSUE TITLE
Parallel view- Nagamese Bible  stuck at loading

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#61]
Issue Description :In parallel view, on selecting Nagamese, it says loading and the screen is stuck and moving to other tabs is not possible unless the app is restarted.  Note: The Nagamese Bible is accessible from the main menu.    
Note :This is a regression and was not observed in the previous test release
Steps:
Select a language and book
Select the parallel Bible and choose Nagamese
Observation:
The right pane says Loading and does not load the Nagamese Bible.
The screen is stuck and does not allow access to any feature.
Note : The App is to be restarted to access the App again
Expected Result: On selecting Nagamese, the Nagamese Bible should load 
![Nagamese Parallel Bible stuck at loading](https://user-images.githubusercontent.com/74647279/107844729-0fd90880-6dfc-11eb-8f00-87c584a8b4a3.jpg)

**Comment by neetuy** [comment]
Fixed issue in release 1.1.0
