### ISSUE TITLE
Infographics Alert  -unavailable spelling , checkout spacing to be corrected

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#62]
Issue description: The infographics alert should have the spelling and spacing corrected 
Steps:
Select a language for which Infographics is not available
Observation:
The alert saying No infographics available appears at the top as expected
However, the following words should be corrected -unavailable 
The word check and out should have a space between them.
![VG-Infographics-Alert message is displayed only for few seconds]
(https://user-images.githubusercontent.com/74647279/108335624-2c5cb280-71f9-11eb-8ee1-0b32d4d63a90.jpg)

**Comment by neetuy** [comment]
Issue has been fixed in 1.1.1 release.
