### ISSUE TITLE
Center Icon of network Unavailable and also in night mode text " offline, content unavailable"  color should be white.

### ISSUE THREAD

**Issue by neetuy** [Bridgeconn/VachanAppReact#64]

**Comment by AnnCherianA** [comment]
Verified the issue and attached screenshots
![Verified Night mode -Color of Offline content unavailable is dark](https://user-images.githubusercontent.com/74647279/112140848-91416900-8bfa-11eb-9fc9-965617a97287.jpg)
![Verified Day mode-Offline content message appears bright](https://user-images.githubusercontent.com/74647279/112140873-97cfe080-8bfa-11eb-92c2-cfd8ab90b7d7.jpg)

**Comment by neetuy** [comment]
Issue has been fixed in release 1.1.1
