### ISSUE TITLE
With Nag on left pane  , in parallel view,  select OT book ,NT book displays 

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#65]
Issue description: 
In the latest version of Vachan app, -1.1.0i  in parallel view , select Nagamese , then on selecting OT book say Genesis 3 , it displays an NT book say Matthew 3
Steps:
In the parallel view, select Nagamese 
Then select an OT book on the other pane- say Genesis
Observation:
The first available  NT book ie Matthew displays instead of the selected OT book
![VG- With Nag on left , select OT book ,NT book displays](https://user-images.githubusercontent.com/74647279/109666186-f8887200-7b94-11eb-8d90-dc2ce4031a6e.jpg)

**Comment by neetuy** [comment]
Issue has been fixed in release 1.1.1
