### ISSUE TITLE
Alert incorrectly displayed -This book will be available soon- initially planned for  OT books when Naga is selected in parallel view

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#66]
Issue description:
The alert -'This book will be available soon ' is incorrectly displayed for all books in the right parallel pane when Nagamese is on the left.
Steps:
In the parallel view, select Nagamese
Then select any book on the right
Observation:
The alert -'This book will be available soon ' is incorrectly displayed for all books in the right parallel pane when Nagamese is on the left.
Expectation:
This alert should appear only for OT books when Nagamese is on the parallel pane.

**Comment by neetuy** [comment]
Fixed Issue
