### ISSUE TITLE
The last chapter of some books are overlapping with the checkmark in the chapter selector drop down.

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#67]
**Issue Description ;**
The last chapter of some books such as (Matthew 28) is overlapping with the check mark in the chapter selector grid.-
Steps:
Select any version -say English ASV
Select  a book and the last chapter of the book -say Matthew 28

**Observation:**
The last chapter -28 overlaps with the check mark which does not allow the last chapter to be selected.
The check mark (indicating Action Done and redirection to previous screen) 
Expected:
There should be enough spacing such that the last chapter can be selected.
![Last chapter overlaps and cannot be selected](https://user-images.githubusercontent.com/74647279/110304063-26e8d000-8021-11eb-9cad-a8e5a7f53455.jpg)

**Comment by neetuy** [comment]
Fixed
