### ISSUE TITLE
 Unable to switch to next chapter in parallel view  from right pane, when the last chapter of the book in left pane is displayed 

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#68]
Issue Description ;

In the parallel view, the navigator ( right arrow) does not appear for the book in the right pane when the chapter in the left pane is the last chapter
Steps:
Select any version -say English ASV
Select the last chapter of a book - Mark 16
Choose the parallel icon - and select any book say English ASV-Matthew
Observation:
In the parallel view, Matthew 16 would be displayed
However, navigation to the next chapter from the right pane is not possible
Analysis:- It is only when the last chapter is selected on the left pane that further navigation is blocked from right pane >
It is not possible to navigate from Matthew 17-28.
Expected:
Navigation to further chapters in right pane should be displayed even when last chapter is selected in left pane
![VG -Last chapter in left pane in parallel pane does not allow further navigation in right pane](https://user-images.githubusercontent.com/74647279/110308068-a9738e80-8025-11eb-80f3-edb5ee077325.jpg)
.

**Comment by neetuy** [comment]
Issue has been fixed in release 1.1.1
