### ISSUE TITLE
Incorrect Alert - Book not available in Null appears  in parallel view -On selecting a text and not performing any action.

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#69]
Issue Description ;

On selecting a text without performing any action (Highlight/Notes/Share) and upon immediately selecting a book from parallel view. 
Incorrect alert - The book you are reading is not available in Null-   The selection made during test was Hindi IRV.  We can remove this alert. 
Steps:
Open any book - Hindi IRV- John 1
Select any text

Observation:
The color tray appears 
Without performing  any action (Highlight/Notes/Share) , switch to parallel view
Observation :
The reminder alert: Your text is selected ,please perform an action.
Now in the parallel drop down ,select a book say English ASV
Observation : The below alert appears 
The book you are reading is not available is null , which is incorrect.
Expected:
The selected book English ASV is available and hence the alert is incorrect and should not be displayed. 
It should display the selected book. 
![VG-Alert incorrect -Null book selection](https://user-images.githubusercontent.com/74647279/110310224-4fc09380-8028-11eb-9293-e725f66830a2.jpg)

**Comment by neetuy** [comment]
Fixed
