### ISSUE TITLE
Right arrow Navigation enhancement:  OT end-> NT start,  chapter end -> next book 

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#73]
Issue Description ;

i) The chapter navigator- right arrow issue not being displayed for the parallel view when one of the panes has the last chapter of the book is now resolved.  (Eg Left pane -Mark 16 ,Right pane-Matthew 28 is now possible) 
          Enhancement /Suggestion: -  
It would be better if right arrow is enabled to display the next book after the last chapter of a book is over as shown below: - Eg the right arrow should  be displayed to allow navigation to Matthew 28 to Mark 1 and vice-versa
ii )Also ,it would be better if end of OT points to NT beginning via right arrow navigation Eg a right arrow navigation from Malachi last chapter to first chapter of Matthew 
Steps:
Open any book - Hindi IRV-
Select the last chapter of a book say Matthew 28.

Observation:
It is not possible to navigate to the  the next book :and chapter ie Mark 1
Expected :
Displaying a right arrow would help navigate to the next book and chapter
Displaing a right arrow should help naviate from OT end to NT beginning 
![Enhancement- OT end NT start - enable navigator arrows](https://user-images.githubusercontent.com/74647279/112138260-4ffb8a00-8bf7-11eb-936c-c47d9160b218.jpg)

**Comment by neetuy** [comment]
We are taking it as enhancement 1.3.0 .

**Comment by AnnCherianA** [comment]
Right arrow navigation moves fine on moving from NT to OT and vice  versa
