### ISSUE TITLE
Enhancement; Replace checkmark icon at the end of chapter grid with a back arrow

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#74]
The issue of last chapter overlapping with the checkmark at the end is now resolved.
          Enhancement: -
 The function of the check mark on this screen is to move to the previous screen. Hence, it is better to replace the check mark with a back arrow. (<---)

Steps:
In Vachan App, select  a book which has all four columns of the chapter grid filled  say Matthew 
Now select any chapter - say 27
Observation :
There is a checkmark meaning the selection of chapter is completed and move to previous screen
Exepcted :
It is better to replace the checkmark with back arrow which clearly guides the user to move to the previous screen

**Comment by AnnCherianA** [comment]
The checkmark currently helps to switch to the book that the user was reading .

**Comment by samuelanthrayose** [comment]
@AnnCherianA We are replacing this issue with #97, right?

**Comment by AnnCherianA** [comment]
@samuelanthrayose  Please find below my understanding of our discussion on these issues 
Issue #97 is about the _**book selector view**_ where the check mark  icon at the footer ,does not have any  particular function and  hence it is to be removed. 
In this issue #74, it is about _**the chapter grid view**_, where the checkmark  icon  upon clicking , switches  to the  previous screen to the book that the user was reading .  Instead of a  checkmark, a back arrow icon is better suited to perform this function .
From the  link that @neetuy shared - 
https://oblador.github.io/react-native-vector-icons/, 
the below icon seemed ideal as a back arrow to switch to the previous screen.  
![image](https://user-images.githubusercontent.com/74647279/122098262-423c5600-ce2e-11eb-8a50-3222b1c56c7d.png)
Is this ok. Please share your thoughts and suggest a better icon if any from this link -https://oblador.github.io/react-native-vector-icons/

**Comment by samuelanthrayose** [comment]
Okay @AnnCherianA I understand. This seems ok, but not sure if the placement of the back arrow in the place of checkbox will look good from a UX perspective. Usually back arrows should be somewhere on the top header or top left of the page. You may want to explore the position of the back arrow.

**Comment by AnnCherianA** [comment]
There is already a back arrow on the top left as well. 
The checkmark is now removed . @samuelanthrayose please check if this is ok.
![VG-Replaced checkmark with backarrow](https://user-images.githubusercontent.com/74647279/125442495-f501f84e-4a60-489f-bd7a-175ebc3daa43.jpg)

**Comment by samuelanthrayose** [comment]
@AnnCherianA Looks fine.
