### ISSUE TITLE
Enhancement: The message please select the book can be replaced by The book you are reading is not available in Nagamese

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#75]
iii)The below issues reported  with Revant Cherian Idikulay's help have been resolved
The alert screen which was placed in the incorrect screen  "The book you were reading is not available in Nagamese' is now resolved and correctly aligned.
        Enhancement: 
The message 'Please select the book' is not appropriate to this context. So it is better to display only the message the book you are reading is not available in Nagamese

**Comment by neetuy** [comment]
Fixed
