### ISSUE TITLE
Google auth issues1 - The Vachan test app project (duplicate)  had to be deleted  as the SHA key from the existing project was being used for authentication. 

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#77]
Issue Description ;
Unable to sign up using Google authentication feature.- SHA key same as existing project for duplicate test project created.
Duration:
Identified post release, after upload to Play store
Rootcause:
The Vachan test app project (duplicate)  had to be deleted  as the SHA key from the existing project was being used for authentication. 
Developer analysis notes :

FIx related notes :
 https://stackoverflow.com/questions/24160011/the-signing-fingerprint-you-specified-is-already-used-by-another-android-oauth2

**Comment by neetuy** [comment]
Fixed issue in 1.1.1 release. It was issue of firebase SHA1 duplicate key as there was an duplicate app for testing,To fix this issue I removed duplicate app from firebase .
