### ISSUE TITLE
Google auth issues2  - The Vachan test app project (duplicate) had to be deleted as the SHA key from the existing project was being used for authentication. 

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#78]
Google auth issues2 - Unable to access Google auth feature -The user is able to login only once . Future logins would not display the Google sign up feature.

Duration:
Identified post release

Developer analysis notes :
 Here I'm sharing apk after fixing the issue, actually issue was because of the api for google login from google(pop-up screen with google account options), that was coming only at once at first time google login but not coming second time, that's why user was not able to see the option for google account. 
Rolled out a new version -1.1.1 on playstore

**Comment by neetuy** [comment]
Fixed. It was issue of firebase SHA1 duplicate key as there was an duplicate app for testing,To fix this issue I removed duplicate app from firebase .
