### ISSUE TITLE
Left arrow navigation issues-  NT beg point to  OT end .  Chapter beg should point to Previous book last chapter 

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#79]
Enhancement /Suggestion: -
It would be better if left arrow is enabled to navigate from 
first chapter of a book to last chapter of the previous book - Mark 1 to Matthew 28
ii )Also ,it would be better if beginning of NT ie Matthew 1 points to last chapter of OT ie Malachi 
Steps:
Open any version - Hindi IRV-
Select the last chapter of OT in Malachi 

Observation:
It is not possible to navigate from Matthew 1st chapter to last chapter of Malachi.
Expected :
Displaying a left arrow would help navigate from first chapter of a book to last chap of previous book 
Displaying a left arrow should help navigate from NT beginning to OT end

**Comment by neetuy** [comment]
We are taking it as enhancement for 1.3.0

**Comment by AnnCherianA** [comment]
Left arrow navigation works fine on moving from NT to OT  and vice-versa
