### ISSUE TITLE
Incorrect alert to be removed for English versions and the correct alert to be updated 

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#81]
The message ' To download bible click on download icon'  appears for the English versions- KJV,ESV and ASV. Since it was decided to remove the download option for these Bibles, we can remove this message.
  ie  we can  remove the message to download the icon and add the below  message for those versions where download icon is not available. 
--This version is not currently available for download. 

![Vachan Go- Notification to be removed for English versions](https://user-images.githubusercontent.com/74647279/119802241-0469a300-befc-11eb-899d-4f5f055f5af3.jpg)

**Comment by neetuy** [comment]
Fixed issue.

**Comment by AnnCherianA** [comment]
Issue resolved and verified
