### ISSUE TITLE
Unable to select the last language in the list on single click - A margin or space may help display the last Bible

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/VachanAppReact#86]
In the language list ,on selecting Assamese version, the Bible does not display on a single click. This may be to do with the screen resolution . Providing a margin / better spacing may help display the Assamese Bible , just like the other Bibles.

**Comment by neetuy** [comment]
It is not issue of margin, if you expand the last item of list it is expanding item but not scrolling it to up as list is expanding downward so it is not visible ,for that user have to scroll up the list.

**Comment by AnnCherianA** [comment]
still feel selecting Urdu (the last language ) in the language drop down is not that easy 
@neetuy @samuelanthrayose  can we please discuss further and check if we can close this issue

**Comment by AnnCherianA** [comment]
Moving to Done as discussed, the user has to scroll down toview the last language
